version: "3.9"
services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    env_file:
      - .env

  pg_admin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - "5050:80"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
